# Default Fairness Metrics Configuration
fairness_metrics:
  demographic_parity:
    threshold: 0.1           # Acceptable maximum disparity between groups
  equal_opportunity:
    threshold: 0.1           # Maximum acceptable difference in true positive rates
  overall_accuracy:
    min_acceptable: 0.75     # Minimum overall accuracy for a model to be considered fair

# Bias Mitigation Parameters
mitigation:
  reweighting:
    enabled: true
    method: "inverse_frequency"   # Sample weights computed as max(label frequency)/frequency(label)
  adversarial_debiasing:
    enabled: true
    # Placeholder parameters for adversarial debiasing (to be tuned for production)
    num_epochs: 50
    learning_rate: 0.01

# Privacy Evaluation Parameters
privacy:
  differential_privacy:
    noise_multiplier: 1.1
    batch_size: 64
    epochs: 10
    delta: 1e-5

# Explainability Parameters
explainability:
  shap:
    sample_size: 10         # Number of training samples to use for KernelExplainer
  lime:
    num_features: 2         # Number of features to display in the explanation summary
